# Generated by Django 5.0.3 on 2025-01-23 06:50

import django_resized.forms
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[200, 200], upload_to=users.models.user_avatar_path),
        ),
    ]
